services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: blazesnow/caddy:cloudflare-alpine
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
