FROM golang:alpine AS builder

RUN go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

WORKDIR /build

RUN xcaddy build --with github.com/caddy-dns/cloudflare

FROM alpine:latest

COPY --from=builder /build/caddy /usr/bin/caddy

ENTRYPOINT [ "/usr/bin/caddy" ]

CMD ["version"]
