name: Docker Publish

on:
  workflow_dispatch:
  schedule:
  - cron: "0 16 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in
      uses: docker/login-action@v3
      with:
        username: blazesnow
        password: ${{ secrets.TOKEN }}
        logout: true

    - name: Set up golang
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: go install xcaddy
      run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

    - name: Make output directory
      run: mkdir -p /build

    - name: xcaddy build
      run: xcaddy build --with github.com/caddy-dns/cloudflare --output /build/caddy

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        dockerfile: Dockerfile
        context: .
        push: true
        tags: blazesnow/caddy:cloudflare-alpine
